### ISSUE TITLE
Cannot get reply to memoryService.requestSpaceLength call

### ISSUE THREAD

**Issue by jeff-tcs** [bobjacobsen/python-openlcb#44]
I am currently retrieving a far node's memory image data via a call to MemoryReadMemo(NodeID(nodeID.id), 64, 0xFF, 0,
                                        memoryReadFail, memoryReadSuccess)
I am getting replies with the callback "memoryReadSuccess". I know that all frames have been received by checking for a < 64 bytes message content length and a 0 byte terminator. I have tried calling memoryService.requestSpaceLength(0xFF, NodeID(nodeID.id), callback=memorySpaceCallback) and when I have a debug breakpoint in the memorySpaceCallback method the breakpoint is never reached. For example if I send a request to the TCS CS and monitor the lights I noticed some activity with the data light for a short while but it seems to never return a reply back to me. Can this memory service call be "ignored" by a far node? It seems like that is the case. I would like to use the requestSpaceLength return value as part of my logic for a Progress GUI widget in the UI. Please advise. Thanks.

**Comment by jeff-tcs** [comment]
Title should have been "Cannot get reply to memoryService.requestSpaceLength call"

**Comment by bobjacobsen** [comment]
The far node shouldn't be ignoring that request.  Can you please check on the CAN bus to make sure the request is going out and the reply is coming back?  I'm away from hardware for a bit, but should be able to test this tomorrow night.

**Comment by jeff-tcs** [comment]
From the way the data light is flickering I believe the request is getting
to the Command Station...not exactly scientific I know...but I could
probably put some breakpoints in the memoryservice code for sending the
request and looking for the returning reply in the code. If you think that
might help diagnose the issue

**Comment by bobjacobsen** [comment]
@jeff-tcs I just pushed `example_memory_length_query.py` for an example of how to do a memory query.  

That same PR fixes a bug in processing the memory length query.  

Could you pull the `main` branch to pick those up?  Thanks, and sorry for the trouble.

**Comment by jeff-tcs** [comment]
Bob thank you for reaching out. I'll try the example and let you know the
results.
Also I will try doing the length request with my dev code and let you know
the results.
What was the bug / problem that you found?

**Comment by jeff-tcs** [comment]
Bob I pulled the python-openlcb branch but did not receive the
example_memory_length_query.py
code file.

**Comment by jeff-tcs** [comment]
I got the memoryservice.py file update but not the
example_memory_length_query.py
<https://github.com/bobjacobsen/python-openlcb/blob/main/example_memory_length_query.py>
 file

**Comment by jeff-tcs** [comment]
Bob,
I got my memoryService.requestSpaceLength(0xFF, NodeID(nodeID.id),
callback=memorySpaceCallback)
code running but I had to also put a time.sleep(1) in before the request
was initiated. Then it started to run
and my follow on code doing the memMemo = MemoryReadMemo(NodeID(nodeID.id),
64, 0xFF, 0,
memoryReadFail, memoryReadSuccess) kicked in as normal.
But the memorySpaceCallback(length) oode is receiving a memory space length
of 0 bytes.

I also copied the example_memory_length_query.py code down from Github (had
to cut and paste it into a visual studio file).
It also returns a memory space length of 0 bytes. So my callback is now
returning but with a 0 byte length. And I see that the request is getting
to the
TCS Command Station with a return.

**Comment by bobjacobsen** [comment]
That return of 0 length is one of the things I fixed in the memoryservice.py file.  Could you try copying that one down from GitHub to see if that fixes it for you?  Sounds like something went wrong in your `git pull` and you didn't get either update. 

https://github.com/bobjacobsen/python-openlcb/blob/main/openlcb/memoryservice.py

**Comment by jeff-tcs** [comment]
Ok will do I have to get with Jake tomorrow and figure it out why I am
having trouble pulling stuff from openlcb.
Thanks

**Comment by jeff-tcs** [comment]
Ok with the new copy of memoryservice.py I am getting the node memory image byte length. Thanks.
New subject. Do you have example code for me that would give an idea of how I should  basically take a CDI change update and write it back to a location in the far node memory image?

**Comment by bobjacobsen** [comment]
> Do you have example code for me that would give an idea of how I should basically take a CDI change update and write it back to a location in the far node memory image?

The tricky part of that is figuring out the address of each variable described by the CDI.  You have to parse the CDI XML, keeping track of the address as you go through each element.  I don't have that code in Python.  The Java version is here:

https://github.com/openlcb/OpenLCB_Java/tree/master/src/org/openlcb/cdi/jdom

This Python implementation was made from the Swift implementation, which has a more Python-like structure:

https://github.com/bobjacobsen/OpenlcbLibrary/tree/main/Sources/OpenlcbLibrary/XML

Are you trying to write a general CDI tool? Or something more specific?

**Comment by jeff-tcs** [comment]
I am writing code for a new application that initially will provide a
general CDI tool capability

cross platform which will allow a user to query for a far node ID list in
an LCC Network. Then select

a specific far node and retrieve it’s memory configuration image. First
level detail will be the display of

SNIP (mfg’s and user info) and Protocol Support information. Second level
detail will again include mgf’s

info and user related elements along with the entire display of the
remaining CDI elements that can be

viewed / changed by the user. The user can then change the content of a
specific CD element(s)

and subsequently send the changed element(s) content back to the far node
to update its memory image.

Code is written in python and I am using KivyMD widgets for the GUI user
interface allowing for “touch”

and / or  “mouse” activation / navigation on the screen over multiple
hardware platforms. I am using the

built-in xml.sax parser with either a regular handler or scream handler
(haven’t decided yet).


I have been to-date looking at how you do the parsing in
CdiParserDelegate.swift within OpenlcbLibraryXML directory as a guide to
writing the parsing code.

It looks like you are grabbing an address from the 'origin' attribute of
the start element to save for future reference. Is that the only place
where an address value is

specified? So far I don't see any address value referenced otherwise. Also
in my parser handler do I need to have the same number of 'cases' to break
down on

for processing the XML content?


I will start looking at your links for further understanding on creating
the parser code.

Can you suggest specific OlcbTools/shared swift View code examples that
might help me understand how best to

take element(s) info from the GUI and prepare it for sending the element
update thru a memory write request call.


I appreciate you guidance in all the above.

**Comment by bobjacobsen** [comment]
Thanks for the info. To answer some specific questions:

> It looks like you are grabbing an address from the 'origin' attribute of the start element to save for future reference. Is that the only place where an address value is specified? So far I don't see any address value referenced otherwise. 

Each of the integer, float, event and string elements increments the address, and the enclosing group element can cause that to happen multiple times.  So you have to keep track of that as you parse the XML.

> Also in my parser handler do I need to have the same number of 'cases' to break down on for processing the XML content?

I don't know.  I think you have to parse everything to follow the addresses, see above.  But there are probably multiple ways to set up that code.

> Can you suggest specific OlcbTools/shared swift View code examples that might help me understand how best to take element(s) info from the GUI and prepare it for sending the element update thru a memory write request call.

For your choice of interface widgets, I think the closest thing is probably

https://github.com/openlcb/OpenLCB_Java/blob/master/src/org/openlcb/cdi/swing/CdiPanel.java

That takes the CDI representation and visits through it to create the corresponding GUI elements.

**Comment by jeff-tcs** [comment]
This is very helpful and enlightening. For the moment I think I have
everything I need to move forward. Thanks.
